server:
  port: 8888
spring:
  application:
    name: eureka-server
eureka:
  client:
    #是否将自己注册到Eureka-Server中，默认的为true
    register-with-eureka: false
    #是否从Eureka-Server中获取服务注册信息，默认为true
    fetch-registry: false