# 服务端口号
server:
  port: 8085

# 服务名
spring:
  application:
    name: oauth2-server
  main:
    #当遇到同样名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: xx
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
# eureka
eureka:
  client:
    serviceUrl:
      #注册到eureka服务端的地址
      defaultZone: http://localhost:8888/eureka/
